metrics-port: 9940
collection-interval-ticks: 20

server_metrics:
  enabled: true
  metrics:
    mspt_milliseconds: true
    tps: true
    tick_time_milliseconds: true
    players_online: true
    players_max: true
    current_tick: true
    worlds: true

world_metrics:
  enabled: true
  metrics:
    players: true
    loaded_chunks: true
    entities: true
    entities_by_category: true
    tile_entities: true
    ticking_tile_entities: true
    time: true
    storm: true
    thundering: true

player_metrics:
  enabled: true
  metrics:
    ping_milliseconds: true
    health: true
    max_health: true
    food_level: true
    saturation: true
    xp_level: true
    xp_progress: true
    total_experience: true
    flying: true
    gamemode: true

jvm_metrics:
  enabled: true
